services:
  - type: web
    name: gestura
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app_web:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
